import { bundle } from 'luabundle';
import luamin from 'luamin';
import fs from 'fs';
import path from 'path';

function bundleNSMM(name, luaFilePath) {
    let bundledLuaOG = bundle(luaFilePath, {
        paths: [luaDir+'/?.lua'],
    });

    console.log('Bundled Lua code length:', bundledLuaOG.length);

    function convertSpecialChars(luaCode) {
        for (let iter = 3; iter > 0; iter--) {
            const regex = new RegExp(`\\\\([0-9]{${iter}})[\\\\ A-z@%]`, 'g');

            luaCode = luaCode.replace(regex, (match, digits) => {
                const num = String(parseInt(digits, 10));
                return match.replace(digits, num);
            });
        };
        return luaCode;
    };

    let bundledLua = convertSpecialChars(convertSpecialChars(bundledLuaOG));

    console.log('Converted special characters in Lua code length:', bundledLua.length, (bundledLua.length / bundledLuaOG.length * 100).toFixed(2) + '% of original size');

    const minifiedLua = 
    `--nSMM Bundle
    --Generated by nSMM Lua Bundler to reduce file size and improve loading performance
    --Full source available at https://github.com/onlypuppy7/nSMM
    `
    +luamin.minify(bundledLua);

    console.log('Minified Lua code length:', minifiedLua.length, (minifiedLua.length / bundledLuaOG.length * 100).toFixed(2) + '% of original size');

    const outputBundleFilePath = path.resolve(`dist/${name}.build.lua`);
    const outputMinifiedFilePath = path.resolve(`dist/${name}.min.build.lua`);

    fs.mkdirSync(path.dirname(outputBundleFilePath), { recursive: true });

    fs.writeFileSync(outputBundleFilePath, bundledLua);
    fs.writeFileSync(outputMinifiedFilePath, minifiedLua);
    console.log('Bundled Lua code written to:', outputBundleFilePath);
    console.log('Minified Lua code written to:', outputMinifiedFilePath);
};

const luaDir = 'src/lua';

bundleNSMM('nSMM', path.resolve(luaDir+'/nsmm.lua'));
bundleNSMM('nSMM.debug', path.resolve(luaDir+'/nsmm-debug.lua'));

bundleNSMM('nSMMCourseWorld', path.resolve(luaDir+'/courseworld.lua'));
// bundleNSMM('nSMMCourseWorld.debug', path.resolve(luaDir+'/courseworld-debug.lua'));