require("polyfill.class")

require("polyfill.platform")

require("polyfill.clipboard")
require("polyfill.cursor")
require("polyfill.d2editor")
require("polyfill.document")
require("polyfill.gc")
require("polyfill.image")
require("polyfill.locale")
require("polyfill.math")
require("polyfill.on")
require("polyfill.string")
require("polyfill.timer")
require("polyfill.toolpalette")
require("polyfill.touch")
require("polyfill.var")
require("polyfill.window")