require("love2d.polyfill.class")

require("love2d.polyfill.platform")

require("love2d.polyfill.clipboard")
require("love2d.polyfill.cursor")
require("love2d.polyfill.d2editor")
require("love2d.polyfill.document")
require("love2d.polyfill.gc")
require("love2d.polyfill.image")
require("love2d.polyfill.locale")
require("love2d.polyfill.math")
require("love2d.polyfill.on")
require("love2d.polyfill.string")
require("love2d.polyfill.timer")
require("love2d.polyfill.toolpalette")
require("love2d.polyfill.touch")
require("love2d.polyfill.var")